/**
 * 樱色日记 ～Sakura Diary～
 * 完整剧情脚本：公共线 + 三条角色线 + 多结局
 */
window.STORY = {
  meta: {
    title: "樱色日记",
    subtitle: "Sakura Diary",
    version: "1.0.0",
  },

  characters: {
    misaki: {
      id: "misaki",
      name: "樱井 美咲",
      color: "#d46a7a",
      sprites: {
        smile: "assets/char/char-misaki-smile.png",
        shy: "assets/char/char-misaki-shy.png",
      },
    },
    haruka: {
      id: "haruka",
      name: "月野 遥",
      color: "#7a8bb8",
      sprites: {
        neutral: "assets/char/char-haruka-neutral.png",
        smile: "assets/char/char-haruka-smile.png",
      },
    },
    rin: {
      id: "rin",
      name: "青山 凛",
      color: "#5a9e7a",
      sprites: {
        cool: "assets/char/char-rin-cool.png",
        smile: "assets/char/char-rin-smile.png",
      },
    },
  },

  backgrounds: {
    title: "assets/bg/bg-title.png",
    gate: "assets/bg/bg-school-gate.png",
    classroom: "assets/bg/bg-classroom.png",
    hallway: "assets/bg/bg-hallway.png",
    courtyard: "assets/bg/bg-courtyard.png",
    library: "assets/bg/bg-library.png",
    rooftop: "assets/bg/bg-rooftop.png",
    festival: "assets/bg/bg-festival.png",
    clubroom: "assets/bg/bg-clubroom.png",
  },

  gallery: [
    { id: "cg_misaki", title: "美咲 · 樱下的约定", src: "assets/cg/cg-misaki-ending.png", unlock: "ending_misaki_good" },
    { id: "cg_haruka", title: "遥 · 窗边的午后", src: "assets/cg/cg-haruka-ending.png", unlock: "ending_haruka_good" },
    { id: "cg_rin", title: "凛 · 晚风与心跳", src: "assets/cg/cg-rin-ending.png", unlock: "ending_rin_good" },
    { id: "bg_gate", title: "回忆 · 校门", src: "assets/bg/bg-school-gate.png", unlock: "seen_gate" },
    { id: "bg_festival", title: "回忆 · 学园祭", src: "assets/bg/bg-festival.png", unlock: "seen_festival" },
    { id: "bg_rooftop", title: "回忆 · 天台", src: "assets/bg/bg-rooftop.png", unlock: "seen_rooftop" },
  ],

  endings: {
    ending_misaki_good: {
      badge: "GOOD END · 樱井美咲",
      title: "樱色的约定",
      text: "在樱花再次盛开的那年春天，你与美咲并肩走过校门。她笑着说——这一次，要一起写下更长的日记。",
      bg: "assets/cg/cg-misaki-ending.png",
    },
    ending_misaki_bad: {
      badge: "BAD END · 樱井美咲",
      title: "未寄出的信",
      text: "班级活动结束的那天，美咲把一封信塞进你的抽屉，却始终没有等到你的回应。樱花落尽时，她的笑容也淡了些。",
      bg: "assets/bg/bg-courtyard.png",
    },
    ending_haruka_good: {
      badge: "GOOD END · 月野遥",
      title: "只读给你听的故事",
      text: "图书馆的角落多了一本只属于你们的笔记本。遥轻声说，以后的每一页，都想和你一起写完。",
      bg: "assets/cg/cg-haruka-ending.png",
    },
    ending_haruka_bad: {
      badge: "BAD END · 月野遥",
      title: "合上的书页",
      text: "你错过了那次重要的邀约。此后在图书馆再遇见遥时，她只是点点头，把视线重新落回书页——像什么都没有发生过。",
      bg: "assets/bg/bg-library.png",
    },
    ending_rin_good: {
      badge: "GOOD END · 青山凛",
      title: "跑向你的直线",
      text: "终赛的哨声落下，凛没有看计分板，而是径直跑向围栏边的你。晚风里，她第一次把心跳坦白得如此清楚。",
      bg: "assets/cg/cg-rin-ending.png",
    },
    ending_rin_bad: {
      badge: "BAD END · 青山凛",
      title: "擦肩的终点线",
      text: "你总是站在安全的观众席。凛赢得了比赛，却在颁奖后独自离开。你们之间，始终差那一步跨出的勇气。",
      bg: "assets/bg/bg-rooftop.png",
    },
    ending_lonely: {
      badge: "NORMAL END",
      title: "一个人的放学路",
      text: "转学生活平稳而安静。你交到了朋友，却没有走进任何人的心里。樱花季节结束时，日记本上仍是空白的一页。",
      bg: "assets/bg/bg-school-gate.png",
    },
  },

  /**
   * 节点格式：
   * { id, bg?, char?, expr?, speaker?, text, next?, choices?, effect?, chapter?, unlock?, affection?, cg?, ending? }
   */
  nodes: {
    // ========== 序章 ==========
    start: {
      chapter: "序章　转学生的春天",
      bg: "gate",
      unlock: "seen_gate",
      speaker: "",
      text: "四月。樱花几乎要把整条通学路淹没。\n我站在「樱丘学院」的校门前，行李还不沉，心跳却已经有点乱。",
      next: "prologue_1",
    },
    prologue_1: {
      bg: "gate",
      speaker: "我",
      text: "「……好，新的开始。」\n我深吸一口气，迈步走了进去。花瓣擦过肩头，像在悄悄说欢迎。",
      next: "prologue_2",
    },
    prologue_2: {
      bg: "hallway",
      speaker: "",
      text: "走廊里还残留着开学典礼的热闹余温。\n我摸出班级指引，在拐角差点撞上一个抱着一摞资料的身影——",
      next: "meet_misaki_1",
    },
    meet_misaki_1: {
      bg: "hallway",
      char: "misaki",
      expr: "smile",
      speaker: "？？？",
      text: "「哇！对、对不起！你没事吧？」\n栗色的短发微微晃着，她手忙脚乱地稳住资料，抬头看我。",
      next: "meet_misaki_2",
    },
    meet_misaki_2: {
      bg: "hallway",
      char: "misaki",
      expr: "shy",
      speaker: "？？？",
      text: "「啊……你是今天的转学生吧？我是二年级的樱井美咲，班级委员。\n欢迎来到樱丘！有什么不懂的尽管问我！」",
      next: "meet_misaki_3",
    },
    meet_misaki_3: {
      bg: "hallway",
      char: "misaki",
      expr: "smile",
      speaker: "我",
      text: "「谢谢，麻烦你了。我叫……」\n我报上名字，她眼睛一下子亮起来，像刚点亮的春日窗光。",
      next: "meet_misaki_4",
    },
    meet_misaki_4: {
      bg: "classroom",
      char: "misaki",
      expr: "smile",
      speaker: "樱井 美咲",
      text: "「这边这边！你的座位在窗边哦。\n说起来下午有自我介绍……别紧张，大家都很友善的！」",
      affection: { misaki: 1 },
      next: "prologue_class",
    },
    prologue_class: {
      bg: "classroom",
      speaker: "",
      text: "自我介绍在轻微的掌声里结束。\n午休铃响时，教室逐渐空下来，只剩阳光在课桌上慢慢挪移。",
      next: "choice_lunch",
    },
    choice_lunch: {
      bg: "classroom",
      speaker: "",
      text: "第一天的午休——要怎么度过？",
      choices: [
        { text: "在教室整理书包，再熟悉一下环境", next: "lunch_class", affection: { misaki: 1 } },
        { text: "去走廊走走，看看学校布局", next: "lunch_hall", affection: { rin: 1 } },
        { text: "找找图书馆，安静待一会儿", next: "lunch_lib", affection: { haruka: 1 } },
      ],
    },

    // --- 午休分支合流 ---
    lunch_class: {
      bg: "classroom",
      char: "misaki",
      expr: "smile",
      speaker: "樱井 美咲",
      text: "「还在呀？我带了点心，要不要分你一点？\n转校第一天肯定累吧，补充点糖分！」",
      next: "lunch_merge",
    },
    lunch_hall: {
      bg: "hallway",
      char: "rin",
      expr: "cool",
      speaker: "？？？",
      text: "「喂，别堵在正中间。」\n一个扎着高马尾的女生从我身边掠过，运动外套的下摆带起一阵风。",
      next: "lunch_hall_2",
    },
    lunch_hall_2: {
      bg: "hallway",
      char: "rin",
      expr: "cool",
      speaker: "？？？",
      text: "她回头看了我一眼，像在确认什么，又迅速移开视线。\n「……转学生？别迷路就行。」",
      next: "lunch_merge",
    },
    lunch_lib: {
      bg: "library",
      char: "haruka",
      expr: "neutral",
      speaker: "",
      text: "图书馆很安静。窗边的座位坐着一位长发女生，正低头读着厚厚的书。\n阳光落在她发丝上，像一层淡淡的雾。",
      next: "lunch_lib_2",
    },
    lunch_lib_2: {
      bg: "library",
      char: "haruka",
      expr: "neutral",
      speaker: "？？？",
      text: "她察觉到视线，轻轻抬眼。\n「……有什么事吗？」声音很轻，却不冷。",
      next: "lunch_merge",
    },
    lunch_merge: {
      bg: "courtyard",
      speaker: "",
      text: "午后，我在中庭的樱树下稍作停留。\n花瓣落在笔记本的空白页上——像在催促我，快写下什么。",
      next: "day1_after",
    },

    // ========== 第一日放学 ==========
    day1_after: {
      chapter: "第一章　三人的轮廓",
      bg: "classroom",
      char: "misaki",
      expr: "smile",
      speaker: "樱井 美咲",
      text: "「放学后要不要我带你逛逛？\n中庭、天台、还有自动售货机藏得最深的角落——本校秘境导览！」",
      next: "choice_day1",
    },
    choice_day1: {
      bg: "classroom",
      char: "misaki",
      expr: "shy",
      speaker: "",
      text: "美咲期待地看着我。",
      choices: [
        { text: "好啊，麻烦你带路", next: "tour_misaki", affection: { misaki: 2 } },
        { text: "我想自己先随便走走", next: "tour_alone", affection: { misaki: -1 } },
      ],
    },
    tour_misaki: {
      bg: "courtyard",
      char: "misaki",
      expr: "smile",
      speaker: "樱井 美咲",
      text: "「看！这棵樱树是学校的标志。每年拍毕业照都在这儿。\n……嘿嘿，说不定明年我们也会站在这里呢。」",
      next: "tour_misaki_2",
    },
    tour_misaki_2: {
      bg: "rooftop",
      unlock: "seen_rooftop",
      char: "misaki",
      expr: "shy",
      speaker: "樱井 美咲",
      text: "「天台要小心门禁啦。不过夕阳真的很棒……\n我有时候会一个人上来整理心情。」",
      affection: { misaki: 1 },
      next: "day1_evening",
    },
    tour_alone: {
      bg: "hallway",
      speaker: "",
      text: "我婉拒了美咲，独自在走廊里游荡。\n拐角处传来运动鞋摩擦地面的声音。",
      next: "meet_rin_1",
    },
    meet_rin_1: {
      bg: "clubroom",
      char: "rin",
      expr: "cool",
      speaker: "青山 凛",
      text: "「哦，是你。中午那个堵路的。」\n她靠在社团室门边，把水瓶拧紧，「我是田径部的青山凛。有事？」",
      next: "meet_rin_2",
    },
    meet_rin_2: {
      bg: "clubroom",
      char: "rin",
      expr: "cool",
      speaker: "我",
      text: "「只是随便看看。你在训练？」",
      next: "meet_rin_3",
    },
    meet_rin_3: {
      bg: "clubroom",
      char: "rin",
      expr: "smile",
      speaker: "青山 凛",
      text: "「差不多。新人欢迎会那种客套话我不会说。\n不过——」她停顿一瞬，「跑过跑道的人，我都认得。」",
      affection: { rin: 2 },
      next: "day1_evening",
    },
    day1_evening: {
      bg: "gate",
      speaker: "",
      text: "放学的人潮渐渐散去。\n我站在校门口，忽然觉得这座学校并不陌生——只是还缺几笔真正的颜色。",
      next: "day2_start",
    },

    // ========== 第二日 ==========
    day2_start: {
      chapter: "第二章　靠近的距离",
      bg: "classroom",
      speaker: "",
      text: "第二天。课程比想象中更紧凑，也更生动。\n午后自习时，老师允许自由阅读。",
      next: "day2_lib",
    },
    day2_lib: {
      bg: "library",
      char: "haruka",
      expr: "neutral",
      speaker: "",
      text: "我再次走进图书馆。窗边那位长发女生仍在——\n桌上多了一本摊开的诗集，书签是一片压干的樱花。",
      next: "meet_haruka_1",
    },
    meet_haruka_1: {
      bg: "library",
      char: "haruka",
      expr: "neutral",
      speaker: "月野 遥",
      text: "「……你昨天也来过。」\n她没有抬高音量，却准确无误地记得我。「我是月野遥。图书委员。」",
      next: "meet_haruka_2",
    },
    meet_haruka_2: {
      bg: "library",
      char: "haruka",
      expr: "smile",
      speaker: "月野 遥",
      text: "「如果找书的话，可以告诉我关键字。\n……或者，你也可以什么都不找，只是坐着。这里允许发呆。」",
      affection: { haruka: 2 },
      next: "day2_choice",
    },
    day2_choice: {
      bg: "library",
      char: "haruka",
      expr: "neutral",
      speaker: "",
      text: "遥把一本薄薄的短篇集推到桌沿，像不经意的邀请。",
      choices: [
        { text: "谢谢，我就借这本", next: "day2_read", affection: { haruka: 2 } },
        { text: "聊聊她喜欢的作家", next: "day2_talk", affection: { haruka: 1 } },
        { text: "礼貌道谢后离开", next: "day2_leave" },
      ],
    },
    day2_read: {
      bg: "library",
      char: "haruka",
      expr: "smile",
      speaker: "月野 遥",
      text: "「那是我很喜欢的一本。读完如果有想法……\n可以告诉我。我很少听到别人的读后感。」",
      next: "day2_after",
    },
    day2_talk: {
      bg: "library",
      char: "haruka",
      expr: "smile",
      speaker: "月野 遥",
      text: "她难得多说了几句，关于句子的节奏，关于雨天适合读什么。\n图书馆的空气仿佛也柔软了一些。",
      next: "day2_after",
    },
    day2_leave: {
      bg: "hallway",
      speaker: "",
      text: "我道谢后离开。身后传来轻轻翻页的声音，像把对话轻轻合上。",
      next: "day2_after",
    },
    day2_after: {
      bg: "courtyard",
      char: "misaki",
      expr: "smile",
      speaker: "樱井 美咲",
      text: "「找到你啦！下周开始要筹备学园祭的班级摊位——\n转学生也要被抓壮丁哦？开玩笑的……半开玩笑。」",
      next: "day2_rin",
    },
    day2_rin: {
      bg: "courtyard",
      char: "rin",
      expr: "cool",
      speaker: "青山 凛",
      text: "凛从跑道方向走过来，发梢还带着汗意。\n「学园祭那天田径部有表演赛。有空的话，来看也行。」",
      next: "day2_rin_2",
    },
    day2_rin_2: {
      bg: "courtyard",
      char: "rin",
      expr: "smile",
      speaker: "青山 凛",
      text: "「不是命令。只是……」她别过脸，「观众席太空的话，跑起来没意思。」",
      affection: { rin: 1 },
      next: "route_select_intro",
    },

    // ========== 路线分歧 ==========
    route_select_intro: {
      chapter: "第三章　选择靠近的人",
      bg: "gate",
      speaker: "",
      text: "几天后，学校的空气变得热闹起来。\n学园祭将近，每个人都有自己的忙碌。而我，也必须决定——想把时间交给谁。",
      next: "route_select",
    },
    route_select: {
      bg: "courtyard",
      speaker: "",
      text: "放学后的去向，将悄悄改变之后的故事。",
      choices: [
        { text: "去帮美咲准备班级摊位", next: "misaki_1", route: "misaki", affection: { misaki: 2 } },
        { text: "去图书馆陪遥整理书目", next: "haruka_1", route: "haruka", affection: { haruka: 2 } },
        { text: "去看凛的课余训练", next: "rin_1", route: "rin", affection: { rin: 2 } },
        { text: "今天什么都不做，直接回家", next: "lonely_1", route: "lonely" },
      ],
    },

    // ========== 美咲线 ==========
    misaki_1: {
      chapter: "美咲篇　忙乱的心动",
      bg: "classroom",
      char: "misaki",
      expr: "smile",
      speaker: "樱井 美咲",
      text: "「太好了！人手严重不足！\n你负责贴海报可以吗？啊不对，先帮我看看菜单文案——」",
      next: "misaki_2",
    },
    misaki_2: {
      bg: "classroom",
      char: "misaki",
      expr: "shy",
      speaker: "樱井 美咲",
      text: "她手忙脚乱地在彩纸和胶带之间穿梭，却始终笑着。\n「有你在，感觉一下子安心好多……是不是有点夸张？」",
      affection: { misaki: 1 },
      next: "misaki_3",
    },
    misaki_3: {
      bg: "rooftop",
      unlock: "seen_rooftop",
      char: "misaki",
      expr: "smile",
      speaker: "樱井 美咲",
      text: "忙到黄昏，我们逃上天台透气。\n「其实我偶尔也会怕搞砸。可是一想到大家会笑，就又想继续做下去。」",
      next: "misaki_choice_1",
    },
    misaki_choice_1: {
      bg: "rooftop",
      char: "misaki",
      expr: "shy",
      speaker: "",
      text: "晚风吹乱她的发丝。美咲侧过头看我。",
      choices: [
        { text: "「你已经做得很好了」", next: "misaki_4a", affection: { misaki: 3 } },
        { text: "「别逞强，累了就说」", next: "misaki_4b", affection: { misaki: 2 } },
        { text: "「……天台风景不错」", next: "misaki_4c", affection: { misaki: 0 } },
      ],
    },
    misaki_4a: {
      bg: "rooftop",
      char: "misaki",
      expr: "shy",
      speaker: "樱井 美咲",
      text: "「诶——突然这么正经，我会害羞的啦！」\n她捂着脸，耳尖却悄悄红了。「……谢谢。我记住了。」",
      next: "misaki_festival",
    },
    misaki_4b: {
      bg: "rooftop",
      char: "misaki",
      expr: "smile",
      speaker: "樱井 美咲",
      text: "「你这样讲，反而让我想再努力一点。\n不过……下次累了，我会第一个告诉你。」",
      next: "misaki_festival",
    },
    misaki_4c: {
      bg: "rooftop",
      char: "misaki",
      expr: "smile",
      speaker: "樱井 美咲",
      text: "「是啊，风景很好。」\n她笑了笑，把没说完的话轻轻咽了回去。",
      next: "misaki_festival",
    },
    misaki_festival: {
      chapter: "美咲篇　学园祭",
      bg: "festival",
      unlock: "seen_festival",
      char: "misaki",
      expr: "smile",
      speaker: "樱井 美咲",
      text: "学园祭当天，班级咖啡店异常热闹。\n美咲系着围裙在人群里穿梭，看见我时眼睛一亮：「支援组！你来得正好！」",
      next: "misaki_festival_2",
    },
    misaki_festival_2: {
      bg: "festival",
      char: "misaki",
      expr: "shy",
      speaker: "樱井 美咲",
      text: "打烊后，纸灯笼把夜色染成暖色。\n「能留下来走走吗？我想……谢谢你这些天一直在。」",
      next: "misaki_choice_final",
    },
    misaki_choice_final: {
      bg: "festival",
      char: "misaki",
      expr: "shy",
      speaker: "",
      text: "灯火下，美咲的声音轻得像怕惊动花瓣。",
      choices: [
        { text: "牵起她的手，认真回应心意", next: "misaki_good_check", affection: { misaki: 3 } },
        { text: "笑着说「朋友之间不必客气」", next: "misaki_bad", affection: { misaki: -2 } },
      ],
    },
    misaki_good_check: {
      bg: "courtyard",
      char: "misaki",
      expr: "shy",
      speaker: "樱井 美咲",
      text: "「……我喜欢你。不是委员对转学生的那种，是——\n想把春天以后的日子，都分给你一半的那种。」",
      next: "misaki_good",
      requireAffection: { misaki: 6 },
      failNext: "misaki_bad",
    },
    misaki_good: {
      bg: "courtyard",
      cg: "assets/cg/cg-misaki-ending.png",
      char: null,
      speaker: "樱井 美咲",
      text: "樱树下，她的笑颜比任何海报都耀眼。\n「那……从今天起，我们的日记要写成两个人的了哦。」",
      next: null,
      ending: "ending_misaki_good",
    },
    misaki_bad: {
      bg: "festival",
      char: "misaki",
      expr: "smile",
      speaker: "樱井 美咲",
      text: "「哈哈，也是呢。朋友的谢谢，我就收下啦。」\n她摆摆手，转身走进灯火里，背影有一瞬晃了一下。",
      next: null,
      ending: "ending_misaki_bad",
    },

    // ========== 遥线 ==========
    haruka_1: {
      chapter: "遥篇　安静的章节",
      bg: "library",
      char: "haruka",
      expr: "neutral",
      speaker: "月野 遥",
      text: "「你来了。……谢谢。\n今天要把文艺部捐赠的书重新分类，一个人有点慢。」",
      next: "haruka_2",
    },
    haruka_2: {
      bg: "library",
      char: "haruka",
      expr: "smile",
      speaker: "月野 遥",
      text: "我们并排整理书脊。偶尔指尖相触，她会轻轻顿一下，再若无其事地继续。\n「你的动作很安静。我喜欢这样。」",
      affection: { haruka: 1 },
      next: "haruka_3",
    },
    haruka_3: {
      bg: "courtyard",
      char: "haruka",
      expr: "neutral",
      speaker: "月野 遥",
      text: "整理结束后，她带我走到中庭。\n「我不常出来。但今天的风……适合把读过的句子说给别人听。」",
      next: "haruka_choice_1",
    },
    haruka_choice_1: {
      bg: "courtyard",
      char: "haruka",
      expr: "smile",
      speaker: "",
      text: "遥翻开诗集，停在某一页。",
      choices: [
        { text: "认真听她读完，并分享感受", next: "haruka_4a", affection: { haruka: 3 } },
        { text: "请她再读一首喜欢的", next: "haruka_4b", affection: { haruka: 2 } },
        { text: "说自己其实不太懂诗", next: "haruka_4c", affection: { haruka: 0 } },
      ],
    },
    haruka_4a: {
      bg: "courtyard",
      char: "haruka",
      expr: "smile",
      speaker: "月野 遥",
      text: "「……你的理解很温柔。\n比我预想的，更靠近作者想说的那一层。」她的眼睫微微颤了颤。",
      next: "haruka_festival",
    },
    haruka_4b: {
      bg: "courtyard",
      char: "haruka",
      expr: "smile",
      speaker: "月野 遥",
      text: "她又读了一首关于雨与窗的短诗。\n读完后沉默片刻：「很少有人会要求安可。」",
      next: "haruka_festival",
    },
    haruka_4c: {
      bg: "courtyard",
      char: "haruka",
      expr: "neutral",
      speaker: "月野 遥",
      text: "「不懂也没关系。诗不是考题。」\n她把书合上，语气依旧平稳，只是话题到此为止。",
      next: "haruka_festival",
    },
    haruka_festival: {
      chapter: "遥篇　灯火之外",
      bg: "festival",
      unlock: "seen_festival",
      char: "haruka",
      expr: "neutral",
      speaker: "月野 遥",
      text: "学园祭的喧闹像潮水。遥站在稍远的树影下，朝我轻轻招手。\n「我不喜欢拥挤。……但我想见你。」",
      next: "haruka_festival_2",
    },
    haruka_festival_2: {
      bg: "library",
      char: "haruka",
      expr: "smile",
      speaker: "月野 遥",
      text: "我们逃回闭馆前的图书馆。只开着一盏灯。\n「其实我写了一段话。不是作业。……给你的。」",
      next: "haruka_choice_final",
    },
    haruka_choice_final: {
      bg: "library",
      char: "haruka",
      expr: "smile",
      speaker: "",
      text: "信封很薄，却像装满了整个季节。",
      choices: [
        { text: "打开信，并告诉她「我想一直读下去」", next: "haruka_good_check", affection: { haruka: 3 } },
        { text: "说太晚了，改天再看", next: "haruka_bad", affection: { haruka: -2 } },
      ],
    },
    haruka_good_check: {
      bg: "library",
      char: "haruka",
      expr: "smile",
      speaker: "月野 遥",
      text: "「喜欢一个人，原来是这种感觉。\n像把最安静的章节，留给唯一的读者。」",
      next: "haruka_good",
      requireAffection: { haruka: 6 },
      failNext: "haruka_bad",
    },
    haruka_good: {
      bg: "library",
      cg: "assets/cg/cg-haruka-ending.png",
      char: null,
      speaker: "月野 遥",
      text: "夕光落在她侧脸。遥微笑着，第一次主动握住我的手。\n「那么……下一页，我们一起写。」",
      next: null,
      ending: "ending_haruka_good",
    },
    haruka_bad: {
      bg: "library",
      char: "haruka",
      expr: "neutral",
      speaker: "月野 遥",
      text: "「……这样啊。那就算了。」\n她把信封收回胸前，像把一扇刚开的窗重新关好。",
      next: null,
      ending: "ending_haruka_bad",
    },

    // ========== 凛线 ==========
    rin_1: {
      chapter: "凛篇　直线的勇气",
      bg: "clubroom",
      char: "rin",
      expr: "cool",
      speaker: "青山 凛",
      text: "「来了？那就别站着。计时器拿好。」\n她把秒表丢给我，自己已经走向跑道。「我跑，你记。」",
      next: "rin_2",
    },
    rin_2: {
      bg: "courtyard",
      char: "rin",
      expr: "cool",
      speaker: "",
      text: "凛的步伐干净利落，像把杂念全部甩在身后。\n冲过终点时，她扶着膝盖喘气，却先问：「成绩呢？」",
      next: "rin_3",
    },
    rin_3: {
      bg: "courtyard",
      char: "rin",
      expr: "smile",
      speaker: "青山 凛",
      text: "听完数字，她难得露出一点真正的笑。\n「还行。你记时很稳……比我们经理靠谱。」",
      affection: { rin: 1 },
      next: "rin_choice_1",
    },
    rin_choice_1: {
      bg: "rooftop",
      unlock: "seen_rooftop",
      char: "rin",
      expr: "cool",
      speaker: "",
      text: "训练后，她把我带到天台，扔过来一瓶水。",
      choices: [
        { text: "「你跑步的样子很漂亮」", next: "rin_4a", affection: { rin: 3 } },
        { text: "「下次我也陪你跑」", next: "rin_4b", affection: { rin: 2 } },
        { text: "「田径好辛苦啊」", next: "rin_4c", affection: { rin: 0 } },
      ],
    },
    rin_4a: {
      bg: "rooftop",
      char: "rin",
      expr: "smile",
      speaker: "青山 凛",
      text: "「……漂亮？」她瞪我一眼，耳根却红了。\n「少说怪话。不过——不准收回。」",
      next: "rin_festival",
    },
    rin_4b: {
      bg: "rooftop",
      char: "rin",
      expr: "smile",
      speaker: "青山 凛",
      text: "「行啊。别喊停就行。」\n她拧开水瓶，低声补了一句，「有人一起的话……或许能再快一点。」",
      next: "rin_festival",
    },
    rin_4c: {
      bg: "rooftop",
      char: "rin",
      expr: "cool",
      speaker: "青山 凛",
      text: "「辛苦才有意思。」\n她靠着围栏，话题很快被风吹散。",
      next: "rin_festival",
    },
    rin_festival: {
      chapter: "凛篇　终点之前",
      bg: "festival",
      unlock: "seen_festival",
      char: "rin",
      expr: "cool",
      speaker: "青山 凛",
      text: "表演赛前，凛在检录处找到我。\n「你来了。……站在能看见冲线的位置。别眨眼。」",
      next: "rin_festival_2",
    },
    rin_festival_2: {
      bg: "rooftop",
      char: "rin",
      expr: "smile",
      speaker: "青山 凛",
      text: "比赛结束后，她拉着我上天台，避开欢呼。\n「我跑的时候只看着前方。可冲线那一瞬……我想起你在看。」",
      next: "rin_choice_final",
    },
    rin_choice_final: {
      bg: "rooftop",
      char: "rin",
      expr: "smile",
      speaker: "",
      text: "晚霞把她的轮廓镀成金色。凛难得没有移开视线。",
      choices: [
        { text: "「那从今以后，我也一直看着你」", next: "rin_good_check", affection: { rin: 3 } },
        { text: "「你今天跑得真的很强」", next: "rin_bad", affection: { rin: -1 } },
      ],
    },
    rin_good_check: {
      bg: "rooftop",
      char: "rin",
      expr: "smile",
      speaker: "青山 凛",
      text: "「喜欢这种话，我说不来。\n但如果你愿意——下次起跑，我想把你当成终点。」",
      next: "rin_good",
      requireAffection: { rin: 6 },
      failNext: "rin_bad",
    },
    rin_good: {
      bg: "rooftop",
      cg: "assets/cg/cg-rin-ending.png",
      char: null,
      speaker: "青山 凛",
      text: "她伸手轻轻碰了碰我的手指，像完成一次无声的交接棒。\n「那就这么定了。不准迟到。」",
      next: null,
      ending: "ending_rin_good",
    },
    rin_bad: {
      bg: "rooftop",
      char: "rin",
      expr: "cool",
      speaker: "青山 凛",
      text: "「……强吗。谢谢。」\n她戴上耳机，脚步重新变得干脆。「我先走了。」",
      next: null,
      ending: "ending_rin_bad",
    },

    // ========== 孤独线 ==========
    lonely_1: {
      chapter: "空白篇　未写的一页",
      bg: "gate",
      speaker: "",
      text: "我回家了。书包放在角落，日记本打开又合上。\n窗外的樱花仍在落，只是与我无关。",
      next: "lonely_2",
    },
    lonely_2: {
      bg: "classroom",
      speaker: "",
      text: "此后的日子平静顺利。我完成作业，参加集体活动，也学会和同学点头打招呼。\n只是每当放学铃响，总觉得少了什么人的声音。",
      next: "lonely_3",
    },
    lonely_3: {
      bg: "festival",
      unlock: "seen_festival",
      speaker: "",
      text: "学园祭那天，我独自穿过灯火巷。\n美咲在忙碌，遥在远处翻书，凛在跑道边热身——大家都有自己的位置。",
      next: "lonely_4",
    },
    lonely_4: {
      bg: "gate",
      speaker: "我",
      text: "「下次……也许该主动一点。」\n我这么想着，却把这句话留在了风里。",
      next: null,
      ending: "ending_lonely",
    },
  },
};
